FROM python:3.11-slim

WORKDIR /app

# نصب کتابخانه‌ها اول (برای استفاده بهتر از cache داکر)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# کپی کل پروژه
COPY . .

EXPOSE 8000

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]